# Generated by Django 4.2.3 on 2023-07-19 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_usuario_email_usuario_nome_usuario_senha'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='pontos',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
