# Generated by Django 4.2.3 on 2023-07-19 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_usuario_pontos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='pontos',
            field=models.IntegerField(default=0),
        ),
    ]
